# -*- coding: utf-8 -*-
"""Session_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16TTs9FdnPSWjO2ZujWVNF5b7fz-rRlJA
"""

# The first code in Python Journey
print("Hello World")

print('Thank you for using this script.')

# Printing Integer
print(50)

# printin Boolean Value
print(True)

# string
print("Mustjab")

# Boolean
print(False)

# float value
print(34.67)

"""## **Data Types**


'Mustjab' -> String

10 -> Integer

True -> Bool

False -> Bool

"Mustjab" -> String

34.67 -> Float
"""

"10"

type("10")

type(10)

type("Mustjab")

type(True)

type(0.0)

# print() funcation
# type() funcation
# Data Types
# Comment

"""## **Variables**
 '=' is assigning oerator

 variable value can be any data type  
"""

# assining the vaiable
name = 'Mustjab'

# output of 'name' variable
print(name)

# we can print direct using variable name of variable instead of print funcation in jupyter notebook to
name

# num = 10
# if want to change the value
# num = 20

# use of variable at multiple places
num = 20

num

num

num

num

num

# assining string in variable
subject = "Maths"

# another variable
lanuage = "English"

# we should assing meaningful variable name
subject_1 = "Math"
subject_1

# To avoid override use this method
subject_2 = "English"
subject_2

# we can assign boolean value in varioable
is_male = True

is_male

# cant use like this to using variable name
# cant use special character
# 1_subject = 'Persion'

subjectOne = "english"

type(subjectOne)

