# -*- coding: utf-8 -*-
"""Session_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12rr6w_X9UHmyBuAgYYGFC9vl2lIMxoCK
"""

# can be concatinat
"str" + "str"

1 + 2

# TypeError: unsupported operand type(s) for +: 'int' and 'str'
#1 + 'str'

# Its print two times
2 * 'Str'

10 * ' Str'

# BODMAS

# PEMDAS

# Parentheses Exponents Multiplication Division Addition Subtraction

# Single Division for float values
1 / 1

# Double Division for round value
1 // 1

# Reminder
1 % 4

# ZeroDivisionError: division by zero
#1 / 0

5 / (9 * 2 + 3**4) % 3

3**4

9*2

18 + 81

5 / 99

0.050505050505050504 % 3

4 % 3 / 5

3 / 5

4 % 0.6

# Parentheses Exponents Multiplication Reminder Division Addition Subtraction
4 % 3

1 / 5

pi = 3.14 # constant

r = int(input("Enter the radius : "))
area = pi * r ** 2

area

print(f"The Area of Circle : {area}")

# We can use formulas directly as a variable
print(f"The Area of Circle : {pi * r ** 2}")

print("The Area of Circle : {}".format(pi * r ** 2))

# Task Get User Input and apply + - * /
num_1 = float(input("Enter the first number : "))
num_2 = float(input("Enter the second number : "))
print(f"Your addition is : {num_1 + num_2}\nYour Subtration is : {num_1 - num_2}\nMultiplication is : {num_1 * num_2}\nYour Division is : {num_1 + num_2}\n")

